
# native profile is used because configurations on local file system will be used instead of git
spring:
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          searchLocations: "classpath:/cloud-configs"

server:
  port: 8002
