
server:
  port: 8002

# native profile is used because configurations on local file system will be used instead of git
spring:
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          #Files can not be on classpath to have dynamic refresh working
          searchLocations: "classpath:/cloud-configs"
          #searchLocations: "file:D:/PropsRepo"
        #git:
        #  uri: "https://githun.com/some-properties-repository"
        #  searchPaths: RepostiorySubfolderName
        #  username: name
        #  password: pass

